extends RefCounted
# Generated by tests/prepare_boss_frames.py; do not hand-edit.
const DATA := {
	"void_sentinel": {
		"cell": [
			512,
			448
		],
		"pivot": [
			256,
			400
		],
		"scale_reference_height": 300,
		"frames": [
			{
				"source_bounds": [
					123,
					18,
					478,
					502
				],
				"bounds": [
					152,
					100,
					220,
					300
				]
			},
			{
				"source_bounds": [
					129,
					15,
					493,
					492
				],
				"bounds": [
					141,
					104,
					226,
					296
				]
			},
			{
				"source_bounds": [
					628,
					18,
					967,
					493
				],
				"bounds": [
					164,
					106,
					210,
					294
				]
			},
			{
				"source_bounds": [
					1104,
					15,
					1467,
					492
				],
				"bounds": [
					159,
					104,
					225,
					296
				]
			},
			{
				"source_bounds": [
					132,
					520,
					498,
					994
				],
				"bounds": [
					146,
					106,
					227,
					294
				]
			},
			{
				"source_bounds": [
					620,
					522,
					967,
					994
				],
				"bounds": [
					151,
					107,
					215,
					293
				]
			},
			{
				"source_bounds": [
					1114,
					523,
					1482,
					993
				],
				"bounds": [
					156,
					109,
					228,
					291
				]
			},
			{
				"source_bounds": [
					623,
					29,
					959,
					502
				],
				"bounds": [
					152,
					107,
					208,
					293
				]
			},
			{
				"source_bounds": [
					1130,
					24,
					1477,
					502
				],
				"bounds": [
					148,
					104,
					215,
					296
				]
			},
			{
				"source_bounds": [
					83,
					523,
					535,
					1007
				],
				"bounds": [
					116,
					100,
					280,
					300
				]
			},
			{
				"source_bounds": [
					589,
					527,
					998,
					1007
				],
				"bounds": [
					129,
					102,
					254,
					298
				]
			},
			{
				"source_bounds": [
					1102,
					522,
					1458,
					1007
				],
				"bounds": [
					146,
					99,
					221,
					301
				]
			}
		],
		"matte_methods": [
			"exterior checker matte",
			"exterior checker matte"
		]
	},
	"abyss_warden": {
		"cell": [
			512,
			448
		],
		"pivot": [
			256,
			400
		],
		"scale_reference_height": 300,
		"frames": [
			{
				"source_bounds": [
					56,
					20,
					286,
					331
				],
				"bounds": [
					129,
					100,
					222,
					300
				]
			},
			{
				"source_bounds": [
					446,
					26,
					697,
					330
				],
				"bounds": [
					122,
					107,
					242,
					293
				]
			},
			{
				"source_bounds": [
					826,
					35,
					1086,
					330
				],
				"bounds": [
					131,
					115,
					251,
					285
				]
			},
			{
				"source_bounds": [
					1212,
					26,
					1484,
					331
				],
				"bounds": [
					129,
					106,
					262,
					294
				]
			},
			{
				"source_bounds": [
					38,
					352,
					331,
					664
				],
				"bounds": [
					106,
					99,
					283,
					301
				]
			},
			{
				"source_bounds": [
					428,
					364,
					714,
					664
				],
				"bounds": [
					113,
					111,
					276,
					289
				]
			},
			{
				"source_bounds": [
					822,
					356,
					1085,
					664
				],
				"bounds": [
					114,
					103,
					254,
					297
				]
			},
			{
				"source_bounds": [
					1187,
					412,
					1509,
					666
				],
				"bounds": [
					101,
					155,
					311,
					245
				]
			},
			{
				"source_bounds": [
					29,
					751,
					348,
					996
				],
				"bounds": [
					102,
					164,
					308,
					236
				]
			},
			{
				"source_bounds": [
					401,
					725,
					837,
					995
				],
				"bounds": [
					46,
					140,
					421,
					260
				]
			},
			{
				"source_bounds": [
					842,
					712,
					1212,
					995
				],
				"bounds": [
					78,
					127,
					357,
					273
				]
			},
			{
				"source_bounds": [
					1222,
					687,
					1514,
					997
				],
				"bounds": [
					115,
					101,
					282,
					299
				]
			}
		],
		"matte_methods": [
			"green chroma key"
		]
	},
	"echo_matriarch": {
		"cell": [
			710,
			448
		],
		"pivot": [
			355,
			320
		],
		"scale_reference_height": 300,
		"frames": [
			{
				"source_bounds": [
					21,
					61,
					344,
					376
				],
				"bounds": [
					103,
					86,
					308,
					300
				]
			},
			{
				"source_bounds": [
					391,
					18,
					742,
					374
				],
				"bounds": [
					76,
					47,
					334,
					339
				]
			},
			{
				"source_bounds": [
					759,
					72,
					1124,
					367
				],
				"bounds": [
					63,
					105,
					348,
					281
				]
			},
			{
				"source_bounds": [
					1170,
					80,
					1520,
					373
				],
				"bounds": [
					77,
					107,
					333,
					279
				]
			},
			{
				"source_bounds": [
					38,
					404,
					373,
					704
				],
				"bounds": [
					91,
					100,
					319,
					286
				]
			},
			{
				"source_bounds": [
					411,
					383,
					747,
					704
				],
				"bounds": [
					90,
					80,
					320,
					306
				]
			},
			{
				"source_bounds": [
					784,
					427,
					1134,
					702
				],
				"bounds": [
					77,
					124,
					333,
					262
				]
			},
			{
				"source_bounds": [
					1216,
					438,
					1494,
					704
				],
				"bounds": [
					146,
					133,
					265,
					253
				]
			},
			{
				"source_bounds": [
					16,
					754,
					305,
					1005
				],
				"bounds": [
					135,
					147,
					275,
					239
				]
			},
			{
				"source_bounds": [
					370,
					704,
					788,
					1010
				],
				"bounds": [
					12,
					95,
					398,
					291
				]
			},
			{
				"source_bounds": [
					826,
					726,
					1198,
					1005
				],
				"bounds": [
					56,
					120,
					354,
					266
				]
			},
			{
				"source_bounds": [
					1190,
					731,
					1506,
					1005
				],
				"bounds": [
					109,
					125,
					301,
					261
				]
			}
		],
		"matte_methods": [
			"exterior checker matte"
		]
	},
	"ash_castellan": {
		"cell": [
			512,
			448
		],
		"pivot": [
			256,
			400
		],
		"scale_reference_height": 300,
		"frames": [
			{
				"source_bounds": [
					27,
					20,
					303,
					325
				],
				"bounds": [
					84,
					100,
					271,
					300
				]
			},
			{
				"source_bounds": [
					387,
					20,
					711,
					328
				],
				"bounds": [
					69,
					97,
					319,
					303
				]
			},
			{
				"source_bounds": [
					776,
					27,
					1090,
					328
				],
				"bounds": [
					51,
					104,
					309,
					296
				]
			},
			{
				"source_bounds": [
					1165,
					18,
					1477,
					327
				],
				"bounds": [
					69,
					96,
					307,
					304
				]
			},
			{
				"source_bounds": [
					18,
					352,
					331,
					661
				],
				"bounds": [
					81,
					96,
					308,
					304
				]
			},
			{
				"source_bounds": [
					395,
					355,
					713,
					660
				],
				"bounds": [
					50,
					100,
					313,
					300
				]
			},
			{
				"source_bounds": [
					780,
					352,
					1105,
					662
				],
				"bounds": [
					63,
					95,
					320,
					305
				]
			},
			{
				"source_bounds": [
					1158,
					370,
					1510,
					661
				],
				"bounds": [
					83,
					114,
					346,
					286
				]
			},
			{
				"source_bounds": [
					15,
					692,
					364,
					987
				],
				"bounds": [
					84,
					110,
					343,
					290
				]
			},
			{
				"source_bounds": [
					397,
					701,
					800,
					988
				],
				"bounds": [
					58,
					118,
					396,
					282
				]
			},
			{
				"source_bounds": [
					799,
					726,
					1151,
					990
				],
				"bounds": [
					83,
					140,
					346,
					260
				]
			},
			{
				"source_bounds": [
					1182,
					673,
					1499,
					989
				],
				"bounds": [
					100,
					89,
					312,
					311
				]
			}
		],
		"matte_methods": [
			"green chroma key"
		]
	},
	"hollow_sovereign": {
		"cell": [
			512,
			448
		],
		"pivot": [
			256,
			400
		],
		"scale_reference_height": 300,
		"frames": [
			{
				"source_bounds": [
					31,
					12,
					323,
					360
				],
				"bounds": [
					70,
					100,
					252,
					300
				]
			},
			{
				"source_bounds": [
					408,
					10,
					715,
					359
				],
				"bounds": [
					59,
					99,
					265,
					301
				]
			},
			{
				"source_bounds": [
					788,
					12,
					1125,
					361
				],
				"bounds": [
					34,
					99,
					291,
					301
				]
			},
			{
				"source_bounds": [
					1189,
					11,
					1524,
					362
				],
				"bounds": [
					29,
					97,
					289,
					303
				]
			},
			{
				"source_bounds": [
					30,
					352,
					359,
					680
				],
				"bounds": [
					27,
					117,
					284,
					283
				]
			},
			{
				"source_bounds": [
					403,
					354,
					737,
					688
				],
				"bounds": [
					49,
					112,
					288,
					288
				]
			},
			{
				"source_bounds": [
					783,
					352,
					1095,
					696
				],
				"bounds": [
					57,
					103,
					269,
					297
				]
			},
			{
				"source_bounds": [
					1171,
					360,
					1475,
					693
				],
				"bounds": [
					62,
					113,
					262,
					287
				]
			},
			{
				"source_bounds": [
					23,
					684,
					303,
					1012
				],
				"bounds": [
					115,
					117,
					241,
					283
				]
			},
			{
				"source_bounds": [
					361,
					690,
					768,
					1008
				],
				"bounds": [
					57,
					126,
					351,
					274
				]
			},
			{
				"source_bounds": [
					762,
					694,
					1194,
					1002
				],
				"bounds": [
					2,
					134,
					372,
					266
				]
			},
			{
				"source_bounds": [
					1205,
					687,
					1515,
					1011
				],
				"bounds": [
					50,
					121,
					267,
					279
				]
			}
		],
		"matte_methods": [
			"exterior checker matte"
		]
	},
	"starfall_guardian": {
		"cell": [
			512,
			448
		],
		"pivot": [
			256,
			400
		],
		"scale_reference_height": 300,
		"frames": [
			{
				"source_bounds": [
					68,
					10,
					288,
					357
				],
				"bounds": [
					156,
					100,
					190,
					300
				]
			},
			{
				"source_bounds": [
					416,
					12,
					655,
					358
				],
				"bounds": [
					160,
					101,
					207,
					299
				]
			},
			{
				"source_bounds": [
					780,
					28,
					1018,
					359
				],
				"bounds": [
					151,
					114,
					206,
					286
				]
			},
			{
				"source_bounds": [
					1179,
					16,
					1378,
					359
				],
				"bounds": [
					170,
					103,
					172,
					297
				]
			},
			{
				"source_bounds": [
					68,
					375,
					307,
					717
				],
				"bounds": [
					161,
					104,
					207,
					296
				]
			},
			{
				"source_bounds": [
					420,
					389,
					667,
					717
				],
				"bounds": [
					141,
					116,
					214,
					284
				]
			},
			{
				"source_bounds": [
					792,
					373,
					1003,
					716
				],
				"bounds": [
					161,
					103,
					182,
					297
				]
			},
			{
				"source_bounds": [
					1100,
					421,
					1433,
					716
				],
				"bounds": [
					112,
					145,
					288,
					255
				]
			},
			{
				"source_bounds": [
					26,
					751,
					345,
					1051
				],
				"bounds": [
					118,
					141,
					276,
					259
				]
			},
			{
				"source_bounds": [
					370,
					742,
					727,
					1051
				],
				"bounds": [
					102,
					133,
					309,
					267
				]
			},
			{
				"source_bounds": [
					740,
					745,
					1098,
					1052
				],
				"bounds": [
					101,
					135,
					310,
					265
				]
			},
			{
				"source_bounds": [
					1160,
					724,
					1384,
					1053
				],
				"bounds": [
					159,
					116,
					194,
					284
				]
			}
		],
		"matte_methods": [
			"green chroma key"
		]
	},
	"ember_marshal": {
		"cell": [
			512,
			448
		],
		"pivot": [
			256,
			400
		],
		"scale_reference_height": 300,
		"frames": [
			{
				"source_bounds": [
					99,
					27,
					340,
					334
				],
				"bounds": [
					162,
					100,
					236,
					300
				]
			},
			{
				"source_bounds": [
					460,
					34,
					675,
					333
				],
				"bounds": [
					142,
					108,
					210,
					292
				]
			},
			{
				"source_bounds": [
					846,
					37,
					1060,
					333
				],
				"bounds": [
					150,
					111,
					209,
					289
				]
			},
			{
				"source_bounds": [
					1219,
					36,
					1454,
					332
				],
				"bounds": [
					123,
					111,
					230,
					289
				]
			},
			{
				"source_bounds": [
					70,
					372,
					323,
					659
				],
				"bounds": [
					127,
					120,
					247,
					280
				]
			},
			{
				"source_bounds": [
					462,
					373,
					700,
					659
				],
				"bounds": [
					126,
					121,
					233,
					279
				]
			},
			{
				"source_bounds": [
					839,
					369,
					1048,
					658
				],
				"bounds": [
					108,
					118,
					204,
					282
				]
			},
			{
				"source_bounds": [
					1184,
					363,
					1463,
					659
				],
				"bounds": [
					120,
					111,
					273,
					289
				]
			},
			{
				"source_bounds": [
					84,
					672,
					333,
					985
				],
				"bounds": [
					134,
					94,
					243,
					306
				]
			},
			{
				"source_bounds": [
					425,
					725,
					810,
					985
				],
				"bounds": [
					68,
					146,
					376,
					254
				]
			},
			{
				"source_bounds": [
					832,
					727,
					1191,
					985
				],
				"bounds": [
					81,
					148,
					351,
					252
				]
			},
			{
				"source_bounds": [
					1238,
					675,
					1493,
					985
				],
				"bounds": [
					131,
					97,
					249,
					303
				]
			}
		],
		"matte_methods": [
			"exterior checker matte"
		]
	}
}
