extends RefCounted
# Generated by tests/prepare_attack_atlas.py; tight alpha bounds for grounded VFX.
const CELLS := [
	Rect2(29, 64, 268, 168),
	Rect2(348, 59, 270, 199),
	Rect2(665, 42, 271, 202),
	Rect2(984, 54, 274, 162),
	Rect2(26, 362, 262, 261),
	Rect2(344, 350, 273, 232),
	Rect2(664, 358, 272, 262),
	Rect2(989, 388, 269, 141),
	Rect2(52, 656, 215, 288),
	Rect2(342, 695, 276, 248),
	Rect2(670, 656, 264, 288),
	Rect2(1008, 665, 233, 279),
	Rect2(30, 976, 264, 257),
	Rect2(353, 984, 253, 260),
	Rect2(667, 976, 262, 259),
	Rect2(985, 976, 264, 258),
	Rect2(32, 1404, 272, 81),
	Rect2(338, 1300, 276, 280),
	Rect2(684, 1307, 249, 263),
	Rect2(1002, 1305, 245, 267),
]
