"""Pad the generated RGBA effects into isolated cells; preserve original alpha."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
atlas = Image.new('RGBA', (1280, 1600))
for name, grid, offset in [('enemy_attack_source_v1.png', 4, 0), ('enemy_attack_extra_source_v1.png', 2, 16)]:
    image = Image.open(ROOT / 'art/characters/drafts' / name)
    assert image.mode == 'RGBA', 'Requires genuine generated alpha; do not matte silently'
    for index in range(grid * grid):
        x, y = index % grid, index // grid
        cell = image.crop((round(x * image.width / grid), round(y * image.height / grid),
                           round((x + 1) * image.width / grid), round((y + 1) * image.height / grid)))
        bounds = cell.getchannel('A').getbbox()
        assert bounds, f'Empty effect {index}'
        cell = cell.crop(bounds)
        cell.thumbnail((288, 288), Image.Resampling.LANCZOS)
        target = offset + index
        atlas.alpha_composite(cell, (target % 4 * 320 + (320 - cell.width) // 2,
                                    target // 4 * 320 + (320 - cell.height) // 2))
atlas.save(ROOT / 'art/characters/enemy_attacks_v1.png')
bounds = []
for index in range(20):
    x, y = index % 4 * 320, index // 4 * 320
    # Register the dense painted base, not faint glow/isolated particles below it.
    alpha = atlas.crop((x, y, x + 320, y + 320)).getchannel('A')
    left, top, right, bottom = alpha.point(lambda a: 255 if a > 120 else 0).getbbox()
    bounds.append(f'\tRect2({x + left}, {y + top}, {right - left}, {bottom - top}),')
(ROOT / 'EnemyAttackBounds.gd').write_text('extends RefCounted\n# Generated by tests/prepare_attack_atlas.py; tight alpha bounds for grounded VFX.\nconst CELLS := [\n' + '\n'.join(bounds) + '\n]\n', encoding='utf-8')
print('Prepared 20 padded RGBA attack textures, 1280x1600')
